#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#                æ�’ä»¶ä½œè€… FlailoftheLord.                          #
#        -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                   #
#     æœ‰é—®é¢˜è¯·è�”ç³»ä½œè€…çš„discord  FlailoftheLord#6842               #
#                 æ±‰åŒ–by å†°ä¹‹ç�¿ & Fur_Xia                          #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# ç�«ç„°å¼¹æ˜¯å�¦ä¼šè¿›è¡Œè‡ªç„¶çš„çˆ†ç‚¸ã€‚
# æ³¨æ„�ï¼šå�¯èƒ½æ— æ³•æ¶ˆé™¤å¯¹çŽ¯å¢ƒçš„ç ´å��[å�¯ä»¥ä½¿ç”¨Coreprotectè¾…åŠ©ä»¥æ�¢å¤�]ã€‚
# å¦‚æžœè®¾ç½®ä¸ºtrueï¼Œåˆ™ä»¥ä¸‹å€¼å°†è¢«å¿½ç•¥ã€‚
# å¦‚æžœè®¾ç½®ä¸ºfalseï¼Œåˆ™æ�’ä»¶å°†ä½¿ç”¨ä»¥ä¸‹çˆ†ç‚¸è®¾ç½®
# ç”¨äºŽåˆ›å»ºçˆ†ç‚¸ã€‚
NaturalExplosion: false

# è®¾ç½®æ’žå‡»æ—¶ç�«ç„°å¼¹çš„çˆ†ç‚¸åŠ›ï¼Œå°†å…¶è®¾ç½®ä¸º0ä»¥ç¦�ç”¨
FireballExplosionPower: 3
# å…�ç–«çˆ†ç‚¸çš„æ–¹å�—
ImmuneBlocks:
- "Chest"
- "trapped_chest"
- "ender_chest"

# è¿™æ„�å‘³ç�€ä»»ä½•å��ç§°ä¸­åŒ…å�«å�•è¯�â€œstoneâ€�çš„æ–¹å�—éƒ½ä¸�ä¼šè¢«ç‚¸æ¯�.
ImmuneBlockKeywords:
- "stone"

# è®¾ç½®ç�«ç„°å¼¹å¯¹å®žä½“æˆ–çŽ©å®¶é€ æˆ�çš„ä¼¤å®³é‡�ã€‚
# 1 = ä¸€é¢—å¿ƒ
FireballDamage: 3.5

# è®¾ç½®ç�«ç„°å¼¹æ˜¯å�¦åœ¨æ’žå‡»äº§ç”Ÿç�«ç„°[å�¯èƒ½æœ‰æ­§ä¹‰]
FireballSetFire: true

# å¤§äºŽ0çš„ä»»ä½•æ•°å­—å°†ä½¿ç”¨ä¸�å�Œçš„æœºåˆ¶æ�¥å�‘å°„ç�«ç„°å¼¹ï¼Œä»¥é˜²æ­¢å®ƒæœ‰æ—¶åœ¨æ‚¨çš„å¤´éƒ¨çˆ†ç‚¸ã€‚
LaunchPosition: 0

# æ˜¯å�¦å�¯ä»¥ä»Žå‰¯æ‰‹æŠ•æŽ·ç�«ç„°å¼¹
AllowOffhandThrowing: true

# æ˜¯å�¦åº”è¯¥å…�è®¸çŽ©å®¶ä½¿ç”¨å¸¸è§„çš„ç�«ç„°å¼¹
UseFirecharge: false

# è®¾ç½®å�¯ä»¥ä½¿ç”¨ç�«ç„°å¼¹è·³è·ƒçš„é«˜åº¦ä¸Šé™�
MaxJumpHeight: 8

# ç¦�æ­¢æŠ•æŽ·ç�«ç„°å¼¹çš„ä¸–ç•Œ
NoThrowZones:
- "world_the_end"
- "creative_world"

# å¦‚æžœä¸–ç•Œåœ¨'NoThrowZone'åˆ—è¡¨ä¸­ï¼Œé‚£ä¹ˆå�‘çŽ©å®¶å�‘é€�çš„æ¶ˆæ�¯
NoThrowZoneMessage: "%prefix% &cæ‚¨ä¸�å…�è®¸åœ¨è¿™ä¸ªä¸–ç•Œä¸Šæ‰”ç�«ç„°å¼¹ï¼�"

# æ�’ä»¶ä¿¡æ�¯å‰�ç¼€
# å�ªéœ€åœ¨ä¿¡æ�¯ä¸­åŠ å…¥å� ä½�ç¬¦ ï¼…prefixï¼…ï¼Œå®ƒå°†è¢«è¯¥å‰�ç¼€æ›¿æ�¢ã€‚
Prefix: "&8(&6Fireballs&8)"

ReloadMessage: |-
    %prefix% &aé…�ç½®æ–‡ä»¶å·²é‡�æ–°åŠ è½½,
     &aå¦‚æžœä½ éœ€è¦�æ›´æ”¹ç�«ç„°å¼¹é…�æ–¹ï¼Œè¯·é‡�å�¯æœ�åŠ¡å™¨!

# å¦‚æžœæ²¡æœ‰æ�ƒé™�ï¼Œå�‘é€�ç»™çŽ©å®¶çš„æ¶ˆæ�¯
NoPermissionMessage: "%prefix% &cä½ æ²¡æœ‰æ�ƒé™�æŠ•æŽ·ç�«ç„°å¼¹"

#Sent when the player doesn't have the permission "fireballs.craft"
NoCraftPermission: "%prefix% &cYou don't have permission to craft this."

# æ˜¯å�¦å�‘çŽ©å®¶æ˜¾ç¤ºå†·å�´æ¶ˆæ�¯
CooldownMessageEnabled: true

# å½“'CooldownMessageEnabled'è®¾ç½®ä¸ºtrueæ—¶ï¼Œæ­¤æ¶ˆæ�¯å°†å�‘é€�ç»™çŽ©å®¶
# ä½¿ç”¨å� ä½�ç¬¦ %cooldown% å°†ä¼šè¢«æ›¿æ�¢ä¸ºå†·å�´å‰©ä½™çš„ç§’æ•°
CooldownMessage: "%prefix% &cä½ å¿…é¡»ç­‰å¾… %cooldown% ç§’å�Žæ‰�èƒ½å�‘å°„ç�«ç„°å¼¹"

# ä¸¤æ¬¡ä½¿ç”¨ä¹‹é—´çš„é—´éš”ï¼ˆä»¥ç§’ä¸ºå�•ä½�ï¼‰è®¾ç½®ä¸º0ä»¥ç¦�ç”¨
Cooldown: 1

# ä¸�æƒ³è®©å®ƒçœ‹èµ·æ�¥åƒ�ç�«ç„°å¼¹æžªå�—ï¼Ÿ
# æ›´æ”¹ç�«ç„°å¼¹çš„ç±»åž‹ã€‚
FireballItem: "fire_charge"

# ç�«ç„°å¼¹çš„è‡ªå®šä¹‰æ˜¾ç¤ºå��ç§°
FireballName: "&6ç�«ç„°å¼¹"

# è¿™é‡Œæ˜¯ç�«ç„°å¼¹æ˜¾ç¤ºçš„lore ...
# å�¯ä»¥æ›´å…·éœ€è¦�è¿›è¡Œä¿®æ”¹!! :)
Lore:
- "&7å�³å‡»ä»¥ä¸¢å‡º"
- "&7grief extreme ;)"

# - - -
# è¿™æ˜¯ç�«ç„°å¼¹çš„åˆ¶ä½œé…�æ–¹ï¼�
# å°†AmountGivenè®¾ç½®ä¸ºä»»æ„�æ•°å­—ï¼Œä»¥è®¾ç½®åˆ¶ä½œæ—¶æ‰€ç»™ç‰©å“�çš„æ•°é‡�ã€‚
# æ¯�ä¸€è¡Œåœ¨åˆ¶ä½œè¡¨æ ¼ä¸­ä¸ºä¸€è¡Œï¼ˆ3 x 3ï¼‰
# å°†å­—æ¯�æ›´æ”¹ä¸º'A'å’Œ'I'ä¹‹é—´çš„ä»»ä½•å­—æ¯�ï¼Œç„¶å�Žå®šä¹‰æ¯�ç§�æ��æ–™ç±»åž‹
# å­—æ¯�ä»£è¡¨ä¸‹é�¢çš„æ��æ–™éƒ¨åˆ†
# æ‚¨å�¯ä»¥åœ¨æ­¤å¤„èŽ·å¾—é¡¹ç›®å��ç§°çš„å®Œæ•´åˆ—è¡¨ï¼š
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# - - -
# å¦‚æžœå…¶ä¸­ä¸€é¡¹æ— æ•ˆï¼Œè¯¥æ�’ä»¶å°†åœ¨æŽ§åˆ¶å�°ä¸­å�‘æ‚¨å�‘å‡ºè­¦å‘Šã€‚
CraftingRecipe:
  AmountGiven: 3
  Pattern:
      1: "ABA"
      2: "BCB"
      3: "ABA"
  Materials:
      A: "GUNPOWDER"
      B: "FIREWORK_STAR"
      C: "GHAST_TEAR"
      D: ""
      E: ""
      F: ""
      G: ""
      H: ""
      I: ""
      
      
      
      
      
