#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#                 Plugin by FlailoftheLord.                        #
#        -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                   #
#   for questions please pm me on discord at FlailoftheLord#6842   #
#          Join my discord server for faster support:              #
#                https://discord.gg/wuxW5PS                        #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# Wether the fireball does a natural, Ghast-Initiated explosion.
# if set to true the below values will be ignored.
# if set to false, the plugin will use the below explosion settings 
# for creating the explosion manually.
NaturalExplosion: true

# Set the Explosion Power of the Fireball on impact, set it to 0 to disable
FireballExplosionPower: 3

ImmuneBlocks:
- Cobblestone
- Mossy_Cobblestone
- stone_bricks
- mossy_stone_bricks
- cracked_stone_bricks
- chiseled_stone_bricks
- END_STONE

# BETA Option! This May NOT WORK DEPENDING ON YOUR SPIGOT BUILD!
FireballSpeed: 2.0

# Set the amount of damage the fireball does to an entity or player.
# 1 = one heart
FireballDamage: 3.5

# Set wether the Fireball does fire on impact or not
FireballSetFire: true

# Whether you can throw a fireball from your offhand
AllowOffhandThrowing: true

# Set the maximum number of blocks in height you can jump with a fireball
MaxJumpHeight: 8

# List of worlds where throwing fireballs is NOT allowed
NoThrowZones:
- "world_the_end"
- "creative_world"

# Message sent if the world is a 'No-Throw-Zone'
NoThrowZoneMessage: "%prefix% &cYou're not allowed to throw fireballs in this world!"

#Plugin prefix for messages
# simply put the placeholder  %prefix% in the message, and it will be replaced by this prefix.
Prefix: "&8(&6Fireballs&8)"

ReloadMessage: |- 
    %prefix% &aconfig file successfully reloaded,
     &amake sure to restart the server if changing the fireball recipe!

#Message to send to player if no permissions
NoPermissionMessage: "%prefix% &cYou do not have permission to use this"

# Whether to show cooldown Messages to player or not
CooldownMessageEnabled: true

#Cooldown Message this message is sent to player when above verbose: is set to true
# use the placeholder %cooldown% for the cooldown time in seconds
CooldownMessage: "%prefix% &cYou must wait %cooldown% seconds before throwing this"

# Cooldown between uses in seconds set to 0 to disable
Cooldown: 1

# Custom display name for the Fireball Item
FireballName: "&6Fireball"

# Heres the lore...
# add as many lines as you want!! :>
Lore:
- "&7right click to throw"
- "&7grief extreme ;)"


# Heres the crafting recipe for the Fireballs!
# Set the AmountGiven to any number to set the amount of the item given when you craft it.
# Each line in the Pattern section is one row in the crafting table (3 x 3)
# Change the Letters to anything between 'A' and 'I' then define which material type each
# letter represents in the Materials section below
# You can get a full list of Item names here:
#    https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

# NOTE: SOME ITEM NAMES HAVE CHANGED IN THE 1.13 UPDATE!!
# This will cause some items to not work in 1.12 and lower...
# It is recommended that you only use this plugin with version 1.13 +
# The plugin will give you a warning in the console if one of the items is invalid.
CraftingRecipe:
  AmountGiven: 3
  Pattern:
      1: "ABA"
      2: "BCB"
      3: "ABA"
  Materials:
      A: "GUNPOWDER"
      B: "FIREWORK_STAR"
      C: "GHAST_TEAR"
      D: ""
      E: ""
      F: ""
      E: ""
      H: ""
      I: ""




